version: '3'

services:
  web-python-blue:
    image: python:alpine
    restart: always
    # entrypoint: python -m http.server -d /root/apps-docker/web-python-blue
    command: python -m http.server -d /root/apps-docker/web-python-blue
    volumes:
      - ./web-python-blue:/root/apps-docker/web-python-blue
    ports:
      - 8000:8000

  web-python-yellow:
    image: python:3-alpine
    restart: always
    # entrypoint: python -m http.server -d /root/apps-docker/web-python-yellow
    command: python -m http.server -d /root/apps-docker/web-python-yellow
    volumes:
      - ./web-python-yellow:/root/apps-docker/web-python-yellow
    ports:
      - 8001:8000
  
  web-node-http-server:
    image: node:20-alpine
    restart: always
    # entrypoint: sh -c "cd /root/apps-docker/web-node-http-server && npm start"
    command: sh -c "cd /root/apps-docker/web-node-http-server && npm start"
    volumes:
      - ./web-node-http-server:/root/apps-docker/web-node-http-server
    ports:
      - 8002:3000

  web-node-express-server:
    image: node:lts-alpine
    restart: always
    # entrypoint: sh -c "cd /root/apps-docker/web-node-express-server && npm start"
    command: sh -c "cd /root/apps-docker/web-node-express-server && npm start"
    volumes:
      - ./web-node-express-server:/root/apps-docker/web-node-express-server
    ports:
      - 8003:3000

  ngnix:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ${CONFIG_PATH}/nginx:/etc/nginx
      - ${DATA_PATH}/nginx/www:/usr/share/nginx/html




  